-- Seed data for ALL Preset Attributes
-- Created automatically

INSERT INTO quick_modifiers (id, category, label, snippet, sort_order)
VALUES
  ('body-type-muscular', 'body-type', 'Muscular', 'muscular', 0),
  ('body-type-slender', 'body-type', 'Slender', 'slender', 10),
  ('body-type-curvy', 'body-type', 'Curvy', 'curvy', 20),
  ('body-type-athletic', 'body-type', 'Athletic', 'athletic', 30),
  ('body-type-petite', 'body-type', 'Petite', 'petite', 40),
  ('body-type-voluptuous', 'body-type', 'Voluptuous', 'voluptuous', 50),
  ('body-type-chubby', 'body-type', 'Chubby', 'chubby', 60),
  ('body-type-lean', 'body-type', 'Lean', 'lean', 70),
  ('gender-female', 'gender', 'Female', 'female', 0),
  ('gender-male', 'gender', 'Male', 'male', 10),
  ('gender-non-binary', 'gender', 'Non-binary', 'non-binary', 20),
  ('gender-androgynous', 'gender', 'Androgynous', 'androgynous', 30),
  ('ethnicity-caucasian', 'ethnicity', 'Caucasian', 'caucasian', 0),
  ('ethnicity-asian', 'ethnicity', 'Asian', 'asian', 10),
  ('ethnicity-black', 'ethnicity', 'Black', 'black', 20),
  ('ethnicity-hispanic', 'ethnicity', 'Hispanic', 'hispanic', 30),
  ('ethnicity-middle-eastern', 'ethnicity', 'Middle Eastern', 'middle eastern', 40),
  ('ethnicity-mixed', 'ethnicity', 'Mixed', 'mixed', 50),
  ('height-tall', 'height', 'Tall', 'tall', 0),
  ('height-short', 'height', 'Short', 'short', 10),
  ('height-average-height', 'height', 'Average Height', 'average height', 20),
  ('height-petite', 'height', 'Petite', 'petite', 30),
  ('height-giant', 'height', 'Giant', 'giant', 40),
  ('skin-tone-pale', 'skin-tone', 'Pale', 'pale', 0),
  ('skin-tone-fair', 'skin-tone', 'Fair', 'fair', 10),
  ('skin-tone-tanned', 'skin-tone', 'Tanned', 'tanned', 20),
  ('skin-tone-olive', 'skin-tone', 'Olive', 'olive', 30),
  ('skin-tone-dark-brown', 'skin-tone', 'Dark Brown', 'dark brown', 40),
  ('skin-tone-ebony', 'skin-tone', 'Ebony', 'ebony', 50),
  ('hair-color-blonde', 'hair-color', 'Blonde', 'blonde', 0),
  ('hair-color-brunette', 'hair-color', 'Brunette', 'brunette', 10),
  ('hair-color-black-hair', 'hair-color', 'Black Hair', 'black hair', 20),
  ('hair-color-red-hair', 'hair-color', 'Red Hair', 'red hair', 30),
  ('hair-color-silver-hair', 'hair-color', 'Silver Hair', 'silver hair', 40),
  ('hair-color-pink-hair', 'hair-color', 'Pink Hair', 'pink hair', 50),
  ('hair-color-blue-hair', 'hair-color', 'Blue Hair', 'blue hair', 60),
  ('hair-style-long-wavy', 'hair-style', 'Long Wavy', 'long wavy', 0),
  ('hair-style-short-bob', 'hair-style', 'Short Bob', 'short bob', 10),
  ('hair-style-pixie-cut', 'hair-style', 'Pixie Cut', 'pixie cut', 20),
  ('hair-style-ponytail', 'hair-style', 'Ponytail', 'ponytail', 30),
  ('hair-style-messy-bun', 'hair-style', 'Messy Bun', 'messy bun', 40),
  ('hair-style-bald', 'hair-style', 'Bald', 'bald', 50),
  ('hair-style-braids', 'hair-style', 'Braids', 'braids', 60),
  ('hair-style-dreadlocks', 'hair-style', 'Dreadlocks', 'dreadlocks', 70),
  ('eye-color-blue-eyes', 'eye-color', 'Blue Eyes', 'blue eyes', 0),
  ('eye-color-green-eyes', 'eye-color', 'Green Eyes', 'green eyes', 10),
  ('eye-color-brown-eyes', 'eye-color', 'Brown Eyes', 'brown eyes', 20),
  ('eye-color-hazel-eyes', 'eye-color', 'Hazel Eyes', 'hazel eyes', 30),
  ('eye-color-grey-eyes', 'eye-color', 'Grey Eyes', 'grey eyes', 40),
  ('eye-color-heterochromia', 'eye-color', 'Heterochromia', 'heterochromia', 50),
  ('face-shape-oval-face', 'face-shape', 'Oval Face', 'oval face', 0),
  ('face-shape-round-face', 'face-shape', 'Round Face', 'round face', 10),
  ('face-shape-heart-shaped-face', 'face-shape', 'Heart Shaped Face', 'heart shaped face', 20),
  ('face-shape-square-jaw', 'face-shape', 'Square Jaw', 'square jaw', 30),
  ('expression-smiling', 'expression', 'Smiling', 'smiling', 0),
  ('expression-frowning', 'expression', 'Frowning', 'frowning', 10),
  ('expression-smirking', 'expression', 'Smirking', 'smirking', 20),
  ('expression-angry', 'expression', 'Angry', 'angry', 30),
  ('expression-sad', 'expression', 'Sad', 'sad', 40),
  ('expression-surprised', 'expression', 'Surprised', 'surprised', 50),
  ('expression-seductive', 'expression', 'Seductive', 'seductive', 60),
  ('expression-neutral', 'expression', 'Neutral', 'neutral', 70),
  ('clothing-casual-wear', 'clothing', 'Casual Wear', 'casual wear', 0),
  ('clothing-formal-suit', 'clothing', 'Formal Suit', 'formal suit', 10),
  ('clothing-evening-gown', 'clothing', 'Evening Gown', 'evening gown', 20),
  ('clothing-streetwear', 'clothing', 'Streetwear', 'streetwear', 30),
  ('clothing-swimwear', 'clothing', 'Swimwear', 'swimwear', 40),
  ('clothing-lingerie', 'clothing', 'Lingerie', 'lingerie', 50),
  ('clothing-naked', 'clothing', 'Naked', 'naked', 60),
  ('clothing-sci-fi-armor', 'clothing', 'Sci-fi Armor', 'sci-fi armor', 70),
  ('clothing-fantasy-robes', 'clothing', 'Fantasy Robes', 'fantasy robes', 80),
  ('accessories-glasses', 'accessories', 'Glasses', 'glasses', 0),
  ('accessories-sunglasses', 'accessories', 'Sunglasses', 'sunglasses', 10),
  ('accessories-necklace', 'accessories', 'Necklace', 'necklace', 20),
  ('accessories-earrings', 'accessories', 'Earrings', 'earrings', 30),
  ('accessories-choker', 'accessories', 'Choker', 'choker', 40),
  ('accessories-watch', 'accessories', 'Watch', 'watch', 50),
  ('accessories-hat', 'accessories', 'Hat', 'hat', 60),
  ('makeup-natural-makeup', 'makeup', 'Natural Makeup', 'natural makeup', 0),
  ('makeup-heavy-makeup', 'makeup', 'Heavy Makeup', 'heavy makeup', 10),
  ('makeup-smokey-eyes', 'makeup', 'Smokey Eyes', 'smokey eyes', 20),
  ('makeup-red-lips', 'makeup', 'Red Lips', 'red lips', 30),
  ('makeup-no-makeup', 'makeup', 'No Makeup', 'no makeup', 40),
  ('makeup-goth-makeup', 'makeup', 'Goth Makeup', 'goth makeup', 50),
  ('tattoos-piercings-no-tattoos', 'tattoos-piercings', 'No Tattoos', 'no tattoos', 0),
  ('tattoos-piercings-sleeve-tattoo', 'tattoos-piercings', 'Sleeve Tattoo', 'sleeve tattoo', 10),
  ('tattoos-piercings-neck-tattoo', 'tattoos-piercings', 'Neck Tattoo', 'neck tattoo', 20),
  ('tattoos-piercings-face-tattoo', 'tattoos-piercings', 'Face Tattoo', 'face tattoo', 30),
  ('tattoos-piercings-ear-piercings', 'tattoos-piercings', 'Ear Piercings', 'ear piercings', 40),
  ('tattoos-piercings-nose-ring', 'tattoos-piercings', 'Nose Ring', 'nose ring', 50),
  ('tattoos-piercings-belly-button-piercing', 'tattoos-piercings', 'Belly Button Piercing', 'belly button piercing', 60),
  ('vibe-cute', 'vibe', 'Cute', 'cute', 0),
  ('vibe-sexy', 'vibe', 'Sexy', 'sexy', 10),
  ('vibe-intimidating', 'vibe', 'Intimidating', 'intimidating', 20),
  ('vibe-innocent', 'vibe', 'Innocent', 'innocent', 30),
  ('vibe-mysterious', 'vibe', 'Mysterious', 'mysterious', 40),
  ('vibe-rebellious', 'vibe', 'Rebellious', 'rebellious', 50),
  ('distinguishing-features-freckles', 'distinguishing-features', 'Freckles', 'freckles', 0),
  ('distinguishing-features-dimples', 'distinguishing-features', 'Dimples', 'dimples', 10),
  ('distinguishing-features-scar', 'distinguishing-features', 'Scar', 'scar', 20),
  ('distinguishing-features-birthmark', 'distinguishing-features', 'Birthmark', 'birthmark', 30),
  ('distinguishing-features-beauty-mark', 'distinguishing-features', 'Beauty Mark', 'beauty mark', 40),
  ('age-18-years-old', 'age', '18 years old', '18 years old', 0),
  ('age-25-years-old', 'age', '25 years old', '25 years old', 10),
  ('age-35-years-old', 'age', '35 years old', '35 years old', 20),
  ('age-50-years-old', 'age', '50 years old', '50 years old', 30),
  ('age-elderly', 'age', 'Elderly', 'elderly', 40),
  ('atmosphere-peaceful', 'atmosphere', 'Peaceful', 'peaceful', 0),
  ('atmosphere-chaotic', 'atmosphere', 'Chaotic', 'chaotic', 10),
  ('atmosphere-creepy', 'atmosphere', 'Creepy', 'creepy', 20),
  ('atmosphere-romantic', 'atmosphere', 'Romantic', 'romantic', 30),
  ('atmosphere-cyberpunk', 'atmosphere', 'Cyberpunk', 'cyberpunk', 40),
  ('atmosphere-magical', 'atmosphere', 'Magical', 'magical', 50),
  ('atmosphere-post-apocalyptic', 'atmosphere', 'Post-Apocalyptic', 'post-apocalyptic', 60),
  ('weather-sunny', 'weather', 'Sunny', 'sunny', 0),
  ('weather-raining', 'weather', 'Raining', 'raining', 10),
  ('weather-snowing', 'weather', 'Snowing', 'snowing', 20),
  ('weather-overcast', 'weather', 'Overcast', 'overcast', 30),
  ('weather-thunderstorm', 'weather', 'Thunderstorm', 'thunderstorm', 40),
  ('weather-foggy', 'weather', 'Foggy', 'foggy', 50),
  ('time-of-day-morning', 'time-of-day', 'Morning', 'morning', 0),
  ('time-of-day-high-noon', 'time-of-day', 'High Noon', 'high noon', 10),
  ('time-of-day-golden-hour', 'time-of-day', 'Golden Hour', 'golden hour', 20),
  ('time-of-day-dusk', 'time-of-day', 'Dusk', 'dusk', 30),
  ('time-of-day-midnight', 'time-of-day', 'Midnight', 'midnight', 40),
  ('time-of-day-pre-dawn', 'time-of-day', 'Pre-Dawn', 'pre-dawn', 50),
  ('season-spring', 'season', 'Spring', 'spring', 0),
  ('season-summer', 'season', 'Summer', 'summer', 10),
  ('season-autumn', 'season', 'Autumn', 'autumn', 20),
  ('season-winter', 'season', 'Winter', 'winter', 30),
  ('lighting-natural-sunlight', 'lighting', 'Natural Sunlight', 'natural sunlight', 0),
  ('lighting-neon-lights', 'lighting', 'Neon Lights', 'neon lights', 10),
  ('lighting-candlelight', 'lighting', 'Candlelight', 'candlelight', 20),
  ('lighting-harsh-shadows', 'lighting', 'Harsh Shadows', 'harsh shadows', 30),
  ('lighting-cinematic-lighting', 'lighting', 'Cinematic Lighting', 'cinematic lighting', 40),
  ('lighting-soft-diffused-light', 'lighting', 'Soft Diffused Light', 'soft diffused light', 50),
  ('color-palette-vibrant-colors', 'color-palette', 'Vibrant Colors', 'vibrant colors', 0),
  ('color-palette-muted-tones', 'color-palette', 'Muted Tones', 'muted tones', 10),
  ('color-palette-monochrome', 'color-palette', 'Monochrome', 'monochrome', 20),
  ('color-palette-pastels', 'color-palette', 'Pastels', 'pastels', 30),
  ('color-palette-neon-cyberpunk-colors', 'color-palette', 'Neon Cyberpunk Colors', 'neon cyberpunk colors', 40),
  ('color-palette-warm-earth-tones', 'color-palette', 'Warm Earth Tones', 'warm earth tones', 50),
  ('architecture-modern-skyscraper', 'architecture', 'Modern Skyscraper', 'modern skyscraper', 0),
  ('architecture-gothic-castle', 'architecture', 'Gothic Castle', 'gothic castle', 10),
  ('architecture-cyberpunk-slums', 'architecture', 'Cyberpunk Slums', 'cyberpunk slums', 20),
  ('architecture-rustic-cabin', 'architecture', 'Rustic Cabin', 'rustic cabin', 30),
  ('architecture-sci-fi-space-station', 'architecture', 'Sci-fi Space Station', 'sci-fi space station', 40),
  ('vegetation-lush-jungle', 'vegetation', 'Lush Jungle', 'lush jungle', 0),
  ('vegetation-pine-forest', 'vegetation', 'Pine Forest', 'pine forest', 10),
  ('vegetation-sparse-desert-shrubs', 'vegetation', 'Sparse Desert Shrubs', 'sparse desert shrubs', 20),
  ('vegetation-cherry-blossoms', 'vegetation', 'Cherry Blossoms', 'cherry blossoms', 30),
  ('vegetation-alien-flora', 'vegetation', 'Alien Flora', 'alien flora', 40),
  ('props-scattered-books', 'props', 'Scattered Books', 'scattered books', 0),
  ('props-glowing-crystals', 'props', 'Glowing Crystals', 'glowing crystals', 10),
  ('props-abandoned-cars', 'props', 'Abandoned Cars', 'abandoned cars', 20),
  ('props-smoking-teacup', 'props', 'Smoking Teacup', 'smoking teacup', 30),
  ('props-sword-in-stone', 'props', 'Sword in Stone', 'sword in stone', 40),
  ('depth-endless-horizon', 'depth', 'Endless Horizon', 'endless horizon', 0),
  ('depth-claustrophobic-alley', 'depth', 'Claustrophobic Alley', 'claustrophobic alley', 10),
  ('depth-vast-cavern', 'depth', 'Vast Cavern', 'vast cavern', 20),
  ('depth-infinite-space', 'depth', 'Infinite Space', 'infinite space', 30),
  ('ground-surface-wet-asphalt', 'ground-surface', 'Wet Asphalt', 'wet asphalt', 0),
  ('ground-surface-soft-grass', 'ground-surface', 'Soft Grass', 'soft grass', 10),
  ('ground-surface-sandy-beach', 'ground-surface', 'Sandy Beach', 'sandy beach', 20),
  ('ground-surface-cracked-earth', 'ground-surface', 'Cracked Earth', 'cracked earth', 30),
  ('ground-surface-polished-marble', 'ground-surface', 'Polished Marble', 'polished marble', 40),
  ('setting-urban-city', 'setting', 'Urban City', 'urban city', 0),
  ('setting-deep-forest', 'setting', 'Deep Forest', 'deep forest', 10),
  ('setting-outer-space', 'setting', 'Outer Space', 'outer space', 20),
  ('setting-underwater', 'setting', 'Underwater', 'underwater', 30),
  ('setting-desert-ruins', 'setting', 'Desert Ruins', 'desert ruins', 40),
  ('shot-type-extreme-close-up', 'shot-type', 'Extreme Close Up', 'extreme close up', 0),
  ('shot-type-close-up', 'shot-type', 'Close Up', 'close up', 10),
  ('shot-type-medium-shot', 'shot-type', 'Medium Shot', 'medium shot', 20),
  ('shot-type-cowboy-shot', 'shot-type', 'Cowboy Shot', 'cowboy shot', 30),
  ('shot-type-full-body-length-shot', 'shot-type', 'Full Body length Shot', 'full body length shot', 40),
  ('shot-type-wide-shot', 'shot-type', 'Wide Shot', 'wide shot', 50),
  ('shot-type-extreme-wide-shot', 'shot-type', 'Extreme Wide Shot', 'extreme wide shot', 60),
  ('camera-angle-eye-level', 'camera-angle', 'Eye Level', 'eye level', 0),
  ('camera-angle-low-angle', 'camera-angle', 'Low Angle', 'low angle', 10),
  ('camera-angle-high-angle', 'camera-angle', 'High Angle', 'high angle', 20),
  ('camera-angle-dutch-angle', 'camera-angle', 'Dutch Angle', 'dutch angle', 30),
  ('camera-angle-birds-eye-view', 'camera-angle', 'Birds Eye View', 'birds eye view', 40),
  ('camera-angle-worms-eye-view', 'camera-angle', 'Worms Eye View', 'worms eye view', 50),
  ('camera-height-ground-level', 'camera-height', 'Ground Level', 'ground level', 0),
  ('camera-height-knee-level', 'camera-height', 'Knee Level', 'knee level', 10),
  ('camera-height-waist-level', 'camera-height', 'Waist Level', 'waist level', 20),
  ('camera-height-shoulder-level', 'camera-height', 'Shoulder Level', 'shoulder level', 30),
  ('camera-height-overhead', 'camera-height', 'Overhead', 'overhead', 40),
  ('lens-macro-lens', 'lens', 'Macro Lens', 'macro lens', 0),
  ('lens-standard-lens', 'lens', 'Standard Lens', 'standard lens', 10),
  ('lens-wide-angle-lens', 'lens', 'Wide Angle Lens', 'wide angle lens', 20),
  ('lens-ultra-wide-angle-lens', 'lens', 'Ultra Wide Angle Lens', 'ultra wide angle lens', 30),
  ('lens-telephoto-lens', 'lens', 'Telephoto Lens', 'telephoto lens', 40),
  ('lens-fish-eye-lens', 'lens', 'Fish Eye Lens', 'fish eye lens', 50),
  ('focal-length-14mm', 'focal-length', '14mm', '14mm', 0),
  ('focal-length-24mm', 'focal-length', '24mm', '24mm', 10),
  ('focal-length-35mm', 'focal-length', '35mm', '35mm', 20),
  ('focal-length-50mm', 'focal-length', '50mm', '50mm', 30),
  ('focal-length-85mm', 'focal-length', '85mm', '85mm', 40),
  ('focal-length-200mm', 'focal-length', '200mm', '200mm', 50),
  ('depth-of-field-shallow-depth-of-field-blurry-background', 'depth-of-field', 'Shallow Depth of Field (Blurry Background)', 'shallow depth of field (blurry background)', 0),
  ('depth-of-field-deep-depth-of-field-everything-in-focus', 'depth-of-field', 'Deep Depth of Field (Everything in focus)', 'deep depth of field (everything in focus)', 10),
  ('focus-point-focus-on-eyes', 'focus-point', 'Focus on Eyes', 'focus on eyes', 0),
  ('focus-point-focus-on-hands', 'focus-point', 'Focus on Hands', 'focus on hands', 10),
  ('focus-point-focus-on-foreground-object', 'focus-point', 'Focus on Foreground Object', 'focus on foreground object', 20),
  ('focus-point-focus-on-background', 'focus-point', 'Focus on Background', 'focus on background', 30),
  ('camera-movement-static-camera', 'camera-movement', 'Static Camera', 'static camera', 0),
  ('camera-movement-slow-pan', 'camera-movement', 'Slow Pan', 'slow pan', 10),
  ('camera-movement-tracking-shot', 'camera-movement', 'Tracking Shot', 'tracking shot', 20),
  ('camera-movement-handheld-shake', 'camera-movement', 'Handheld Shake', 'handheld shake', 30),
  ('camera-movement-dolly-zoom', 'camera-movement', 'Dolly Zoom', 'dolly zoom', 40),
  ('composition-rule-rule-of-thirds', 'composition-rule', 'Rule of Thirds', 'rule of thirds', 0),
  ('composition-rule-golden-ratio', 'composition-rule', 'Golden Ratio', 'golden ratio', 10),
  ('composition-rule-symmetry', 'composition-rule', 'Symmetry', 'symmetry', 20),
  ('composition-rule-leading-lines', 'composition-rule', 'Leading Lines', 'leading lines', 30),
  ('composition-rule-center-framing', 'composition-rule', 'Center Framing', 'center framing', 40),
  ('aspect-ratio-16-9-widescreen', 'aspect-ratio', '16:9 widescreen', '16:9 widescreen', 0),
  ('aspect-ratio-9-16-vertical', 'aspect-ratio', '9:16 vertical', '9:16 vertical', 10),
  ('aspect-ratio-1-1-square', 'aspect-ratio', '1:1 square', '1:1 square', 20),
  ('aspect-ratio-2-35-1-cinematic', 'aspect-ratio', '2.35:1 cinematic', '2.35:1 cinematic', 30),
  ('primary-action-running', 'primary-action', 'Running', 'running', 0),
  ('primary-action-jumping', 'primary-action', 'Jumping', 'jumping', 10),
  ('primary-action-fighting', 'primary-action', 'Fighting', 'fighting', 20),
  ('primary-action-dancing', 'primary-action', 'Dancing', 'dancing', 30),
  ('primary-action-sleeping', 'primary-action', 'Sleeping', 'sleeping', 40),
  ('primary-action-crying', 'primary-action', 'Crying', 'crying', 50),
  ('primary-action-laughing', 'primary-action', 'Laughing', 'laughing', 60),
  ('primary-action-casting-magic', 'primary-action', 'Casting Magic', 'casting magic', 70),
  ('body-position-standing-straight', 'body-position', 'Standing straight', 'standing straight', 0),
  ('body-position-crouching', 'body-position', 'Crouching', 'crouching', 10),
  ('body-position-leaning-against-wall', 'body-position', 'Leaning against wall', 'leaning against wall', 20),
  ('body-position-laying-down', 'body-position', 'Laying down', 'laying down', 30),
  ('body-position-mid-air', 'body-position', 'Mid-air', 'mid-air', 40),
  ('body-position-sitting', 'body-position', 'Sitting', 'sitting', 50),
  ('hand-placement-hands-in-pockets', 'hand-placement', 'Hands in pockets', 'hands in pockets', 0),
  ('hand-placement-arms-crossed', 'hand-placement', 'Arms crossed', 'arms crossed', 10),
  ('hand-placement-holding-weapon', 'hand-placement', 'Holding weapon', 'holding weapon', 20),
  ('hand-placement-covering-face', 'hand-placement', 'Covering face', 'covering face', 30),
  ('hand-placement-reaching-out', 'hand-placement', 'Reaching out', 'reaching out', 40),
  ('head-direction-looking-at-camera', 'head-direction', 'Looking at camera', 'looking at camera', 0),
  ('head-direction-looking-away', 'head-direction', 'Looking away', 'looking away', 10),
  ('head-direction-looking-up', 'head-direction', 'Looking up', 'looking up', 20),
  ('head-direction-looking-down', 'head-direction', 'Looking down', 'looking down', 30),
  ('head-direction-looking-over-shoulder', 'head-direction', 'Looking over shoulder', 'looking over shoulder', 40),
  ('facial-expression-grinning', 'facial-expression', 'Grinning', 'grinning', 0),
  ('facial-expression-screaming', 'facial-expression', 'Screaming', 'screaming', 10),
  ('facial-expression-biting-lip', 'facial-expression', 'Biting lip', 'biting lip', 20),
  ('facial-expression-rolling-eyes', 'facial-expression', 'Rolling eyes', 'rolling eyes', 30),
  ('facial-expression-tearful', 'facial-expression', 'Tearful', 'tearful', 40),
  ('motion-blur-heavy-motion-blur', 'motion-blur', 'Heavy Motion Blur', 'heavy motion blur', 0),
  ('motion-blur-slight-motion-blur', 'motion-blur', 'Slight Motion Blur', 'slight motion blur', 10),
  ('motion-blur-crisp-freeze-frame', 'motion-blur', 'Crisp Freeze Frame', 'crisp freeze frame', 20),
  ('energy-level-manic-energy', 'energy-level', 'Manic Energy', 'manic energy', 0),
  ('energy-level-calm-and-relaxed', 'energy-level', 'Calm and Relaxed', 'calm and relaxed', 10),
  ('energy-level-lethargic', 'energy-level', 'Lethargic', 'lethargic', 20),
  ('energy-level-tense', 'energy-level', 'Tense', 'tense', 30),
  ('interaction-hugging', 'interaction', 'Hugging', 'hugging', 0),
  ('interaction-kissing', 'interaction', 'Kissing', 'kissing', 10),
  ('interaction-punching', 'interaction', 'Punching', 'punching', 20),
  ('interaction-shaking-hands', 'interaction', 'Shaking hands', 'shaking hands', 30),
  ('interaction-ignoring', 'interaction', 'Ignoring', 'ignoring', 40),
  ('art-medium-oil-painting', 'art-medium', 'Oil Painting', 'oil painting', 0),
  ('art-medium-watercolor', 'art-medium', 'Watercolor', 'watercolor', 10),
  ('art-medium-pencil-sketch', 'art-medium', 'Pencil Sketch', 'pencil sketch', 20),
  ('art-medium-digital-concept-art', 'art-medium', 'Digital Concept Art', 'digital concept art', 30),
  ('art-medium-35mm-film-photography', 'art-medium', '35mm Film Photography', '35mm film photography', 40),
  ('art-medium-polaroid', 'art-medium', 'Polaroid', 'polaroid', 50),
  ('art-medium-anime-cel', 'art-medium', 'Anime Cel', 'anime cel', 60),
  ('brushwork-or-texture-thick-impasto', 'brushwork-or-texture', 'Thick Impasto', 'thick impasto', 0),
  ('brushwork-or-texture-smooth-gradients', 'brushwork-or-texture', 'Smooth Gradients', 'smooth gradients', 10),
  ('brushwork-or-texture-film-grain', 'brushwork-or-texture', 'Film Grain', 'film grain', 20),
  ('brushwork-or-texture-visible-sketch-marks', 'brushwork-or-texture', 'Visible Sketch Marks', 'visible sketch marks', 30),
  ('brushwork-or-texture-halftone-dots', 'brushwork-or-texture', 'Halftone Dots', 'halftone dots', 40),
  ('influence-or-era-80s-retro', 'influence-or-era', '80s Retro', '80s retro', 0),
  ('influence-or-era-victorian-steampunk', 'influence-or-era', 'Victorian Steampunk', 'victorian steampunk', 10),
  ('influence-or-era-renaissance', 'influence-or-era', 'Renaissance', 'renaissance', 20),
  ('influence-or-era-studio-ghibli', 'influence-or-era', 'Studio Ghibli', 'studio ghibli', 30),
  ('influence-or-era-cyberpunk-2077', 'influence-or-era', 'Cyberpunk 2077', 'cyberpunk 2077', 40),
  ('level-of-detail-hyper-realistic-8k', 'level-of-detail', 'Hyper-realistic 8k', 'hyper-realistic 8k', 0),
  ('level-of-detail-minimalist-flat-colors', 'level-of-detail', 'Minimalist Flat Colors', 'minimalist flat colors', 10),
  ('level-of-detail-impressionistic', 'level-of-detail', 'Impressionistic', 'impressionistic', 20),
  ('level-of-detail-rough-sketch', 'level-of-detail', 'Rough Sketch', 'rough sketch', 30),
  ('key-elements-lens-flares', 'key-elements', 'Lens Flares', 'lens flares', 0),
  ('key-elements-chromatic-aberration', 'key-elements', 'Chromatic Aberration', 'chromatic aberration', 10),
  ('key-elements-vignette', 'key-elements', 'Vignette', 'vignette', 20),
  ('key-elements-glitch-effect', 'key-elements', 'Glitch Effect', 'glitch effect', 30),
  ('key-elements-glowing-aura', 'key-elements', 'Glowing Aura', 'glowing aura', 40)
ON CONFLICT (id) DO NOTHING;
